catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
catalog:
  '@c8y/client': ^1023.68.7
  '@napi-rs/keyring': ^1.2.0
  '@schplitt/eslint-config': ^1.4.0
  '@tmcp/adapter-valibot': ^0.1.5
  '@tmcp/transport-http': ^0.8.5
  '@tmcp/transport-stdio': ^0.4.2
  '@toon-format/toon': ^2.1.0
  '@types/node': ^24.12.2
  bumpp: ^11.0.1
  changelogithub: ^14.0.0
  citty: ^0.2.2
  consola: ^3.4.2
  eslint: ^9.39.4
  h3: 2.0.1-rc.6
  secure-exec: ^0.2.1
  tmcp: ^1.19.3
  tsdown: ^0.21.9
  typescript: ^5.9.3
  ufo: ^1.6.3
  unctx: ^2.5.0
  valibot: ^1.3.1
  vitest: ^4.1.4
onlyBuiltDependencies:
  - better-sqlite3
  - cbor-extract
  - esbuild
  - isolated-vm

